import React from 'react'
import Footer from '../Footer/Footer'
import Navbar from '../Navbar/Navbar'
import "./Terms.css"

export default function Terms() {
  return (
    <div>
        <Navbar></Navbar>
        <section id="terms-of-service">
        <h2 className="primary-heading">Terms of Service</h2>
        <div className="cargd">
            <p className='paragraph'>
            These terms and conditions <span className='bold'>User Terms</span> apply to Your visit to and use, of the Site whether through a computer or a mobile phone, the Service and the Application, as well as to all information, recommendations and or services provided to You on or through the Site, the Service and the Application. This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000.<br></br> This electronic record is generated by a computer system and does not require any physical or digital signatures.
            By clicking on the <span className='bold'>I ACCEPT</span> button or by using Ahen’s services, You are consenting to be bound by these User Terms. <span className='bold'>PLEASE ENSURE THAT YOU READ AND UNDERSTAND ALL THESE USER TERMS BEFORE YOU USE THE SITE.</span> If You do not accept any of the User Terms, then please do not use the Site or avail any of the services being provided therein. <span className='bold'>YOUR AGREEMENT TO THESE USER TERMS SHALL OPERATE AS A BINDING AGREEMENT BETWEEN YOU AND AHEN IN RESPECT OF THE USE AND SERVICES OF THE SITE.</span>
            </p>
            <p className="paragraph">
                1)<span className='bold'>DEFINITIONS</span><br></br>
                All of the defined and capitalized terms in these User Terms will have the meaning assigned to them here below:<br></br>
                (i) <span className='bold'>Account</span> shall mean the account created by the Customer on the Application for availing the Services provided by Ahen.<br></br>
                (ii) <span className='bold'>Applicable Laws</span> shall mean and include all applicable statutes, enactments, acts of legislature or parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines, policies, directions, directives and orders of any governmental authority, tribunal, or a court of India.<br></br>
                (iii) <span className='bold'>Application</span> shall mean the mobile application <span className='bold'>Ahen Admin</span> updated by Ahen from time to time.<br></br>
                (iv) <span className='bold'>Extra charges</span> means charges applied by Ahen and not by any individual.<br></br>
                (v) <span className='bold'>Customer/ You</span> means a person who has an Account on the Application.<br></br>
                (vi) <span className='bold'>T&Cs</span> and <span className='bold'>User Terms</span> shall mean these Customer terms and conditions.<br></br>
                (vii) <span className='bold'>TPSP</span> shall mean a third party service provider.<br></br>
                (viii) <span className='bold'>Vehicle</span> shall mean a motor cab as defined under the Motor Vehicles Act,1988.<br></br>
                <br/>
                2)<span className='bold'>ELIGIBILITY</span><br></br>
                You will be <span className='bold'>Eligible</span> to use the Services only when You fulfill all of the following conditions:<br></br> (i) You have attained at least <span className='bold'>18 (eighteen)</span> years of age. <br></br>(ii) You are competent to enter into a contract under the Applicable Laws.
                If You reside in a jurisdiction that restricts the use of the Service because of age, or restricts the ability to enter into contracts such as this User Terms due to age, You must abide by such age limits

                <br/><br/>
                3)<span className='bold'>REGISTRATION AND ACCOUNT</span>
                <br></br>
                3.1 You understand and acknowledge that You can register on the Site only after complying with the requirements of this Clause 3 and by entering Your Registration Data.
                <br></br>
                3.2 You shall ensure that the Registration Data provided by You is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by You.
                <br></br>
                3.3 We reserve the right to <span className='bold'>suspend or terminate</span> Your Account with immediate effect and for an indefinite period, if We have a reason to believe that the Registration Data or any
                other data provided by You is incorrect or false, or that the security of Your Account has been compromised in any way, or for any other reason We may find just or equitable.

                <br/><br/>
                4)<span className='bold'> SERVICES </span><br></br>
                The Site permits you to avail the multiple services offered by Ahen and/or by a third party.
 
                <br/><br/>
                5) <span className='bold'>USER VIOLATION OF USER TERMS</span><br></br>
                5.1. You shall not <span className='bold'>smoke and drink </span>in the Vehicles or misbehave with the customer or distract the customer or act in violation of Applicable Law. In the event You are found to be involved in the activities set out above,
                You shall be liable to pay a <span className='bold'>fine</span> to us and we shall also have the right to terminate the Ride. In the event You fail to pay fine after the completion of the session, we may at our discretion, take such steps as may be available to us under Applicable Law. You shall also be blacklisted as a result of non-payment of the fine or misbehaving as the case may be, and in such event, Your Account may be terminated by Ahen.
                <br/><br/>
            </p>
        </div>
    
    <Footer></Footer>
    </section>
    </div>
  )
}
